services:
  backend:
    build: .
    ports:
      - "8000:8000"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080